name: Deploy to GitHub Pages
on: [push]
permissions:
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # v3 → v4に更新[1][4]
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-pages-artifact@v2  # v1 → v2に更新[1]
        with:
          path: dist/
      - uses: actions/deploy-pages@v2  # v1 → v2に更新[1]
