name: Deploy to GitHub Pages
on: [push]
permissions:
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # v4が最新[1][5]
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-pages-artifact@v2  # v2が公式推奨（v3存在せず）
        with:
          path: dist/
      - uses: actions/deploy-pages@v2
